# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project_form.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_NewProjectForm(object):
    def setupUi(self, NewProjectForm):
        NewProjectForm.setObjectName("NewProjectForm")
        NewProjectForm.resize(604, 473)
        self.verticalLayout = QtGui.QVBoxLayout(NewProjectForm)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.info_label = QtGui.QLabel(NewProjectForm)
        self.info_label.setMinimumSize(QtCore.QSize(0, 0))
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label.setWordWrap(False)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_5.addWidget(self.info_label)
        self.name_line = QtGui.QFrame(NewProjectForm)
        self.name_line.setFrameShadow(QtGui.QFrame.Plain)
        self.name_line.setFrameShape(QtGui.QFrame.HLine)
        self.name_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.name_line.setObjectName("name_line")
        self.verticalLayout_5.addWidget(self.name_line)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(-1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(NewProjectForm)
        self.label_2.setMargin(1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.name_edit = QtGui.QLineEdit(NewProjectForm)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 1, 1, 1)
        self.name_preview_label = QtGui.QLabel(NewProjectForm)
        self.name_preview_label.setText("")
        self.name_preview_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.name_preview_label.setMargin(1)
        self.name_preview_label.setIndent(-1)
        self.name_preview_label.setObjectName("name_preview_label")
        self.gridLayout.addWidget(self.name_preview_label, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(NewProjectForm)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setMargin(1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtGui.QLabel(NewProjectForm)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.publishes_line = QtGui.QFrame(NewProjectForm)
        self.publishes_line.setFrameShadow(QtGui.QFrame.Plain)
        self.publishes_line.setFrameShape(QtGui.QFrame.HLine)
        self.publishes_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.publishes_line.setObjectName("publishes_line")
        self.verticalLayout_6.addWidget(self.publishes_line)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.publish_list = PublishListView(NewProjectForm)
        self.publish_list.setStyleSheet("#publish_list {\n"
"background-color: rgb(255, 128, 0);\n"
"}")
        self.publish_list.setObjectName("publish_list")
        self.verticalLayout_4.addWidget(self.publish_list)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.add_publish_btn = QtGui.QPushButton(NewProjectForm)
        self.add_publish_btn.setMinimumSize(QtCore.QSize(32, 0))
        self.add_publish_btn.setObjectName("add_publish_btn")
        self.horizontalLayout.addWidget(self.add_publish_btn)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.break_line = QtGui.QFrame(NewProjectForm)
        self.break_line.setFrameShadow(QtGui.QFrame.Plain)
        self.break_line.setFrameShape(QtGui.QFrame.HLine)
        self.break_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.break_line.setObjectName("break_line")
        self.verticalLayout.addWidget(self.break_line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(12, 8, 12, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancel_btn = QtGui.QPushButton(NewProjectForm)
        self.cancel_btn.setMinimumSize(QtCore.QSize(90, 0))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.create_btn = QtGui.QPushButton(NewProjectForm)
        self.create_btn.setMinimumSize(QtCore.QSize(90, 0))
        self.create_btn.setDefault(True)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_3.addWidget(self.create_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(NewProjectForm)
        QtCore.QObject.connect(self.cancel_btn, QtCore.SIGNAL("clicked()"), NewProjectForm.close)
        QtCore.QMetaObject.connectSlotsByName(NewProjectForm)

    def retranslateUi(self, NewProjectForm):
        NewProjectForm.setWindowTitle(QtGui.QApplication.translate("NewProjectForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.info_label.setText(QtGui.QApplication.translate("NewProjectForm", "Please enter a name below to be used as part of the project name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewProjectForm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewProjectForm", "Preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewProjectForm", "Add publishes you would like to include in the new project", None, QtGui.QApplication.UnicodeUTF8))
        self.add_publish_btn.setText(QtGui.QApplication.translate("NewProjectForm", "Add Publish...", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("NewProjectForm", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.create_btn.setText(QtGui.QApplication.translate("NewProjectForm", "Create Project", None, QtGui.QApplication.UnicodeUTF8))

from ..publish_list_view import PublishListView
from . import resources_rc
